### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by lynetcha** [NVIDIA/VisRTX#13]
Hi, I am trying to render the nvidia/vMaterials/Design/Wood/Bubinga.bubinga_chocolate_oiled material (from NVIDIA's vmaterials) using sampleMDL.cpp  but the result I get is different  than what I expected. Any idea what might be wrong?  The logs do not highlight any issues.

Result
<img width="553" alt="Result" src="https://user-images.githubusercontent.com/11138935/74391053-e421dd80-4db7-11ea-88ef-e5c28e9e12f9.png">

Expected
<img width="152" alt="Expected" src="https://user-images.githubusercontent.com/11138935/74391071-f56aea00-4db7-11ea-872d-13e3973a54da.png">

Log
<img width="1322" alt="log" src="https://user-images.githubusercontent.com/11138935/74391078-fac83480-4db7-11ea-892f-f34c3e23fdc8.png">

**Comment by lynetcha** [comment]
The main thing that seems off in the log is that it says that OptiX version is 7.1.0 but I actually downloaded OptiX 6.0.0.

**Comment by tbiedert** [comment]
Thank you for your bug report!

A simple reproducer would be great.  Since you're using sampleMDL.cpp as basis, can you please send me a diff?

Thanks!
Tim

**Comment by lynetcha** [comment]
Here it is. 
[vmat.patch.zip](https://github.com/NVIDIA/VisRTX/files/4197317/vmat.patch.zip)

**Comment by tbiedert** [comment]
Thanks!

The problem is that a sphere geometry does not produce texture coordinates at the hit point as you might expect.   Currently, you can specify a single constant tex coord per sphere.  This has historic reasons from a scientific visualization background. Additionally, there is no canonical sphere surface to 2D texture coord mapping.

In the following screenshot you can see a manually tesselated sphere (TriangleGeometry) with the material's texture correctly applied based on a spherical mapping:

![wood](https://user-images.githubusercontent.com/20560929/74425397-e8033d80-4e53-11ea-94fd-6c88ca1073c7.png)

Modified patch:  [texcoord.zip](https://github.com/NVIDIA/VisRTX/files/4197751/texcoord.zip)

**Comment by lynetcha** [comment]
Thank you!

**Comment by tbiedert** [comment]
Btw, if you need to render many spheres with spherical texture mapping (or any other specific mapping), it shouldn't be complicated to adjust VisRTX's sphere intersection code and simply compute and output the correct texture coordinates at the hit point. Let me know if you need any help with this.

Depending on your scene, you still might be better off with a tesselation, especially on Turing where you have hardware-accelerated triangle intersection.
