### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by lynetcha** [NVIDIA/VisRTX#14]
Hi Tim,

I am trying to make the rendering look photorealistic and I am wondering if you have pointers on how to do that? Attached is what I get with 4 directional lights. The specular highlights don't look very realistic. Any idea on how this can be improved? Thanks.
[lighting.tar.gz](https://github.com/NVIDIA/VisRTX/files/4202288/lighting.tar.gz)

![wood](https://user-images.githubusercontent.com/11138935/74494489-071cc200-4e8a-11ea-9604-3d96fddefebd.png)

**Comment by lynetcha** [comment]
The material above is ::nvidia::vMaterials::Design::Wood::Bubinga::bubinga_chocolate_oiled
Below you can also find ::nvidia::vMaterials::Design::Paint::Gloss::paint_gloss_dark_blue 

<img width="583" alt="Screen Shot 2020-02-13 at 9 05 38 PM" src="https://user-images.githubusercontent.com/11138935/74503359-879cec00-4ea5-11ea-839b-3bd8a0de042d.png">

and ::nvidia::vMaterials::Design::Wood::Bubinga::bubinga_carbonized_matte
<img width="574" alt="Screen Shot 2020-02-13 at 9 07 04 PM" src="https://user-images.githubusercontent.com/11138935/74503378-94214480-4ea5-11ea-99e5-5e5911c12899.png">

I expect them to look like the thumbnails below
::nvidia::vMaterials::Design::Wood::Bubinga::bubinga_chocolate_oiled
<img width="152" alt="Screen Shot 2020-02-13 at 9 10 28 PM" src="https://user-images.githubusercontent.com/11138935/74503398-a307f700-4ea5-11ea-8e7a-1f4baf1edf7d.png">
::nvidia::vMaterials::Design::Paint::Gloss::paint_gloss_dark_blue 
<img width="149" alt="Screen Shot 2020-02-13 at 9 11 27 PM" src="https://user-images.githubusercontent.com/11138935/74503431-b5823080-4ea5-11ea-80ee-221ff1774ac9.png">
::nvidia::vMaterials::Design::Wood::Bubinga::bubinga_carbonized_matte
<img width="148" alt="Screen Shot 2020-02-13 at 9 12 02 PM" src="https://user-images.githubusercontent.com/11138935/74503486-dfd3ee00-4ea5-11ea-9a97-4d43e69c35cd.png">

**Comment by tbiedert** [comment]
Hey Lyne,

above spheres don't look completely photorealistic because the lighting setup is just too perfect / too artificial. The sphere is basically hovering in a perfectly black vaccum with a few perfectly homogeneous white spot lights on them.

In contrast, in the reference images from vMaterials you have an interesting ground plane, which adds shadowing, ambient occlusion, and reflections of the pattern on the material.  Additionally, there is probably some kind of environmental lighting. Think of the sky above your head, where you have radiance bouncing around and coming from all directions, plus maybe a directional sun light.

To achieve the latter in VisRTX, you can add a `HDRILight` to the scene. This will basically add a sphere at infinity around the scene, onto which you can map a radiance emitting texture using a spherical projection. 

Try googling for "hdri image" to get an impression how such textures can look like. If you use an image with high dynamic range, which is useful when it includes bright lighting such as direct sun light, make sure to use the correct texture format, e.g., RGB32F.

Another thing I mentioned above is the perfectly homogeneous directional light. In reality, lights emit radiance following some kind of wavelength-based distribution. Typically used for AEC workflows, this can be captured in so-called IES light profiles. However, VisRTX does not support such advanced light profiles yet.

So for starters, I suggest making the scene a bit more complex with different materials, so you can have a more natural interplay of reflections, shadowing, ambient occusion, etc., and experimenting with some HDRI images in high dynamic range format to simulate some real-world lighting conditions.

Hope that helps!
Tim

**Comment by lynetcha** [comment]
Yes, that was helpful. I got some improvements with HRDI light and a couple of planes. Thank you!
<img width="291" alt="Screen Shot 2020-02-15 at 1 46 00 AM" src="https://user-images.githubusercontent.com/11138935/74585739-f3aa4d80-4f94-11ea-9723-816726770a36.png">
<img width="294" alt="Screen Shot 2020-02-15 at 1 37 50 AM" src="https://user-images.githubusercontent.com/11138935/74585742-fe64e280-4f94-11ea-8d17-3c8ca0153c28.png">
