### ISSUE TITLE
Rendering PBR Materials

### ISSUE THREAD

**Issue by lynetcha** [NVIDIA/VisRTX#17]
Hi Tim,

How can I extend BasicMaterial (or adapt MDLMaterial) to support rendering PBR materials with several maps (displacement, Ambient Occlusion, Metallic, Roughness, etc.). BasicMaterial only has support for a few texture maps. I am trying to load materials similar to [this](https://cc0textures.com/view?id=Rock034) and [this](https://cc0textures.com/view?id=Metal022). Any help is appreciated!

Thanks,

Lyne

**Comment by tbiedert** [comment]
Hi Lyne,

Please check out vMaterials:  https://developer.nvidia.com/vmaterials

That free collection of MDL materials should contain similar materials to what you described.

Note that displacement mapping would need to be supported by the renderer since it modifies the surface intersection. VisRTX only supports bump mapping for MDL surfaces.

Best,
Tim
