### ISSUE TITLE
Implement backface culling as an extension

### ISSUE THREAD

**Issue by jeffamstutz** [NVIDIA/VisRTX#63]
Need to investigate if this is per-device, per-renderer, or per-surface/material/geometry.

**Comment by stukowski** [comment]
From the point of view of the OVITO application, a per-device or a per-renderer setting would be too coarse-grained, since a scene may contain both one-sided and two-sided meshes. 

The other 3 options should all be sufficient for OVITO's purposes, but on the application side, the per-surface variant most closely matches the internal model (which is aligned with OpenGL, where the culling mode is controlled via glEnable/glDisable calls). 

The other two variants could possibly require duplicating the material or the geometry. But the latter is unlikely, as usually the same geometry is not rendered in both modes, and duplicating the material if necessary would not be expensive.

**Comment by progschj** [comment]
Maybe an extension could add the concept of a front and back side material on the surface? Leaving one of those open would then simply not shade the back side and thus "culling" it?
